### PR TITLE
Add GraphQLSchema to the factory

### LINKED ISSUE #14: GraphQLBundle having another override `getGraphQLSchema()`?
I am building the schema via manual objects instead of via the RuntimeWiring and SDL files. However, the GraphQLFactory abstraction that is currently exposed in this plugin requires you to be using RuntimeWiring.

If I put together a PR that added a `getGraphQLSchema()` overridable function that can optionally be used instead would that be accepted?

### PR DESCRIPTION
**Pull request by rcleps**
Fixes #14 

This GraphQLSchema enable the possibility to create dynamic schemas, for example using java graph annotations.

### CODE REVIEW

**Comment by jplock** [comment]
I think this file needs to be relocated into `src/main/java/com/smoketurner/`

**Comment by rcleps** [comment]
You mean outside of dropwizard/graphql ?

**Comment by jplock** [comment]
@rcleps no, you committed and checked in the file at the root of the repository so its not overwriting the existing file.

**Comment by rcleps** [comment]
@jplock you right, my mistake! Done!

**Comment by jplock** [comment]
Thank you for the contribution @rcleps!  I'll try and get a new release tagged later today.

**Comment by jplock** [comment]
Just published `1.3.12-1` with this fix to Maven Central.  Thanks!

**Comment by rcleps** [comment]
Tks a lot, I will help every time I can!

**Pull request merged**
