### PR TITLE
Update GraphQLFactory.java

### PR DESCRIPTION
**Pull request by phact**

### CODE REVIEW

**Comment by jplock** [comment]
Looks like an import is missing or something.  Is it possible to keep returning a `File`?

**Comment by phact** [comment]
Serves me right for trying to ninja that original patch :)

I'm open to suggestions on how to return a File. I ended up dropping this dependency and using a BufferedReader in my project.

**Comment by jplock** [comment]
I wonder if we used `Paths` instead of `File` if we'd have the same issue.  I feel like that's cleaner than the `BufferedReader`.

https://github.com/google/jib/blob/master/examples/helloworld/src/main/java/example/HelloWorld.java#L31

**Comment by apodkutin** [comment]
> I wonder if we used Paths instead of File if we'd have the same issue. I feel like that's cleaner than the BufferedReader.

Hi @jplock thank you for this bundle.
No it will not help, it will throw a new exception:
```
java.nio.file.FileSystemNotFoundException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
	at java.base/java.nio.file.Paths.get(Paths.java:143)
```
It's because `URI` for the file in jar looks like this:
```
jar:file:/home/application/target/application-0.0.1-SNAPSHOT.jar!/graphql/Scheme.graphql
```
It's not a plain path in the filesystem.
So there is no a good way to get file from jar, except `getResourceAsStream` method.

By the way, when you're planning to release a new version with this fix?

**Comment by jplock** [comment]
I'll try to get one out this week.  Sorry for the delay.

**Pull request merged**
